/* To create the DATABASES with ENV (use only once upon deployment)*/
CREATE DATABASE EFAH_DEV_01;

/* make sure to use this first before exec any sql */
use EFAH_DEV_01;


/** CREATE USER TABLES---------*/
/** 
DATE OF REVISION : 10-01-2019
AUTHOR BY : NAPIHUP
PKEY : USER_ID
FKEY : NOT APPLICABLE
*/
CREATE TABLE T_01_EFAH_USER (
	
    ROW_ID INT NOT NULL UNIQUE AUTO_INCREMENT, 
    USER_ID VARCHAR(50) NOT NULL UNIQUE PRIMARY KEY,
    FULLNAME VARCHAR(50),
    EMAIL VARCHAR(50),
    MOBILE_NUM VARCHAR(50),
    USER_TYPE_ID INT NOT NULL
    
);

/** CREATE AUTH TABLES---------*/
/** 
DATE OF REVISION : 10-01-2019
AUTHOR BY : NAPIHUP
PKEY : NOT APPLICABLE
FKEY : USER_ID
*/
CREATE TABLE T_01_EFAH_AUTH (
	
    USER_ID VARCHAR(50) NOT NULL UNIQUE,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(1000) NOT NULL UNIQUE
    
);


/** CREATE USERTYPE TABLE ------*/
/**
DATE OF REVISION : 12-01-2019
AUTHOR BY : NAPIHUP
PKEY : TYPE_ID
*/
CREATE TABLE T_01_EFAH_USER_TYPE (
    TYPE_ID INT NOT NULL PRIMARY KEY UNIQUE AUTO_INCREMENT,
    USER_TYPE VARCHAR(20)
);



/** Testing scripts*/
SELECT * FROM T_01_EFAH_USER_TYPE;

select * from T_01_EFAH_USER;
select * from T_01_EFAH_AUTH;

SELECT 
USER.USER_ID AS USER_ID, USER.FULLNAME AS FULLNAME, USER.EMAIL AS EMAIL, USER.MOBILE_NUM AS MOBILE_NUM, UTYPE.USER_TYPE AS USER_TYPE
FROM T_01_EFAH_USER USER INNER JOIN T_01_EFAH_USER_TYPE UTYPE
ON USER.USER_TYPE_ID = UTYPE.TYPE_ID;

DROP TABLE T_01_EFAH_USER;
DROP TABLE T_01_EFAH_AUTH;

TRUNCATE T_01_EFAH_AUTH;
TRUNCATE T_01_EFAH_USER;


SELECT * FROM T_01_EFAH_AUTH AS AUTH WHERE USERNAME = 'Iffahsf';

select
case when USER.cnt > 0 then 'EXIST' else 'NOT-EXIST' end as count from (
select count(*) as cnt from
(
select * from T_01_EFAH_USER where MOBILE_NUM = '91785ef546' OR EMAIL = 'KHAIfefeRI@GMAIL.COM'
) USER_C
)USER;

select
case when AUTH.cnt > 0 then 'EXIST' else 'NOT-EXIST' end as result from (
select count(*) as cnt from
(
select * from T_01_EFAH_AUTH where USERNAME = '91785ef546' OR PASSWORD = 'bdcaocf7a8ca585acae31242@#%^%^$&879353%*&%(gdg7rgb'
) AUTH_C
)AUTH;
 






